os: Visual Studio 2013

before_build:
# Change working directory and current location
- ps: cd Code
- ps: "[Environment]::CurrentDirectory = $PWD"
# Download & Unzip FastBuild
- ps: (new-object net.webclient).DownloadFile('http://fastbuild.org/downloads/v0.91/FASTBuild-Windows-x64-v0.91.zip', 'C:/FastBuild.zip')
- ps: Add-Type -assembly "system.io.compression.filesystem"
- ps: "[io.compression.zipfile]::ExtractToDirectory('C:/FastBuild.zip', 'C:/FastBuild')"
# Add FastBuild to path
- ps: "$env:Path = $env:Path + ';C:/FastBuild'"
# Generate VS projects
- ps: fbuild solution -noprogress
 
# Using FastBuild
build_script:
- ps: fbuild x86-Release x64-Release -noprogress

# Using MSbuild
#build:
#  project: C:\projects\tmp\VisualStudio\FASTBuild.sln
#  verbosity: minimal
  
after_build:
# zip versions
- ps: cd ..
- ps: 7z a FASTBuild-Windows-x64.zip Code\LICENSE.TXT tmp\x64-Release\Tools\FBuild\FBuildApp\FBuild.exe tmp\x64-Release\Tools\FBuild\FBuildWorker\FBuildWorker.exe
- ps: 7z a FASTBuild-Windows-x86.zip Code\LICENSE.TXT tmp\x86-Release\Tools\FBuild\FBuildApp\FBuild.exe tmp\x86-Release\Tools\FBuild\FBuildWorker\FBuildWorker.exe
#Launch analysis
- ps:  ./SonarQubeAnalysisForAppVeyor.ps1 -sources Code/ -buildWrapperCommand "msbuild  'tmp/VisualStudio/FASTBuild.sln'  /t:rebuild"

artifacts:
- path: FASTBuild-Windows-x64.zip
  name: FASTBuild-Windows-x64
- path: FASTBuild-Windows-x86.zip
  name: FASTBuild-Windows-x86

deploy:
- provider: GitHub
  auth_token:
    secure: 5MDCvsL3LRe8MibH5pObCEEHoST7Ef2RMgfW9C44m/SoiCZZTvUA+AJG9Ieh7HU6
  prerelease: true